add integration test for app

diff --git a/Jenkinsfile.devsecops b/Jenkinsfile.devsecops
--- a/Jenkinsfile.devsecops
+++ b/Jenkinsfile.devsecops
@@ -253,5 +253,49 @@ pipeline {
         )
       }
     }
+    stage ('Integration Test') {
+      agent {
+        kubernetes {
+          defaultContainer 'curl'
+          yaml '''
+            apiVersion: v1
+            kind: Pod
+            spec:
+              containers:
+              - name: curl
+                image: curlimages/curl:8.1.1
+                command:
+                - sleep
+                args:
+                - 99d
+            '''
+        }
+      }
+      steps {
+        sh '''
+        sleep 5s
+
+        # HTTP GET test
+        http_get_code=$(curl -s -o /dev/null -w "%{http_code}" http://${applicationDNS}
+        if [[ "$http_get_code" == 200 ]];
+            then
+                echo "indexHandler Test Passed"
+            else
+                echo "indexHandler Test Failed"
+                exit 1;
+        fi
+
+        # HTTP POST test
+        http_post_code=$(curl --data-raw 'Item=DEVSECOPS' -L -s -o /dev/null -w "%{http_code}" -H 'Content-Type: application/x-www-form-urlencoded' http://${applicationDNS})
+        if [[ "$http_post_code" == 200 ]];
+            then
+                echo "postHandler Test Passed"
+            else
+                echo "postHandler Test Failed"
+                exit 1;
+        fi
+        '''
+      }
+    }
   }
 }
